#!/usr/bin/env python3
"""Turn a downloaded public data-agent benchmark into a `cases.jsonl` that
`agent_eval bench --dir` can run. stdlib only.

Not run in CI and not fully tested against a live download — the field names
below are from each benchmark's published schema; sanity-check the first few
rows after you fetch the data.

    # DABStep (HF: adyen/DABstep) — fetch the `tasks` split as JSONL + its
    # context/ dir, then:
    python3 bench/convert.py dabstep <tasks.jsonl> <context_dir> > bench/dabstep-easy/cases.jsonl
    #   (copy <context_dir>/* alongside the cases.jsonl)

    # InfiAgent-DABench (GitHub: InfiAgent/InfiAgent, da-dev-*.jsonl + csvs/)
    python3 bench/convert.py infiagent <da-dev-questions.jsonl> <csv_dir> > bench/infiagent/cases.jsonl
"""
import json
import re
import sys


def num(s):
    """Best-effort parse of a gold value into a float, else None."""
    if isinstance(s, (int, float)):
        return float(s)
    m = re.search(r"-?\d[\d,]*\.?\d*", str(s))
    return float(m.group(0).replace(",", "")) if m else None


def dabstep(tasks_path, _ctx_dir):
    for line in open(tasks_path):
        line = line.strip()
        if not line:
            continue
        t = json.loads(line)
        if str(t.get("level", "")).lower() != "easy":
            continue
        ans = t.get("answer") or t.get("ground_truth") or ""
        gold = (
            {"figures": [num(ans)]}
            if num(ans) is not None
            else {"contains": [str(ans).strip()]}
        )
        # DABStep easy tasks read from the shared context dir; list the files
        # the task's `guidance` / `question` names, or all of them.
        files = t.get("files") or t.get("context_files") or []
        yield {
            "id": f"dabstep-{t.get('task_id', t.get('id'))}",
            "question": t["question"]
            + ("\n\n" + t["guidance"] if t.get("guidance") else ""),
            "files": files,
            "gold": gold,
            "tier": "easy",
        }


def infiagent(q_path, _csv_dir):
    for line in open(q_path):
        line = line.strip()
        if not line:
            continue
        q = json.loads(line)
        # answers look like "@total_sales[12345.6] @top_region[West]"
        pairs = re.findall(r"@[\w.]+\[([^\]]+)\]", q.get("common_answers") or q.get("answer") or "")
        figs = [num(p) for p in pairs if num(p) is not None]
        strs = [p.strip() for p in pairs if num(p) is None]
        gold = {"figures": figs} if figs else {"contains": strs or ["?"]}
        yield {
            "id": f"infiagent-{q.get('id')}",
            "question": q["question"]
            + ("\n\n" + q["format"] if q.get("format") else ""),
            "files": [q["file_name"]] if q.get("file_name") else [],
            "gold": gold,
            "tier": "easy",
        }


if __name__ == "__main__":
    if len(sys.argv) != 4:
        sys.exit(__doc__)
    fn = {"dabstep": dabstep, "infiagent": infiagent}[sys.argv[1]]
    print("# generated by bench/convert.py " + " ".join(sys.argv[1:]))
    for rec in fn(sys.argv[2], sys.argv[3]):
        print(json.dumps(rec))
